main/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from main import views

app_name = 'main'

urlpatterns = [
    path('', views.IndexView.as_view(), name="index"),
    path('about/', views.AboutView.as_view(), name="about"),
]

orders/urls.py
from django.urls import path
from orders import views

app_name = 'orders'

urlpatterns = [
    path('create_order/', views.CreateOrderView.as_view(), name="create_order"),
]

store/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static

from store import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls', namespace='main')),
    path('catalog/', include('goods.urls', namespace='catalog')),
    path('user/', include('users.urls', namespace='user')),
    path('cart/', include('carts.urls', namespace='cart')),
    path('orders/', include('orders.urls', namespace='orders'))
]

if settings.DEBUG:
    urlpatterns += [
        path("__debug__/", include("debug_toolbar.urls")),

    ]
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

orders/models.py
from django.db import models
from django.utils.translation import gettext_lazy as _

from goods.models import Products
from users.models import User


class OrderitemQuetySet(models.QuerySet):

    def total_price(self):
        return sum(cart.products_price() for cart in self)

    def total_quantity(self):
        if self:
            return sum(cart.quantity for cart in self)
        return 0


class Order(models.Model):
    user = models.ForeignKey(to=User, on_delete=models.SET_DEFAULT, blank=True, null=True, verbose_name=_('User'),
                             default=None)
    created_timestamp = models.DateTimeField(auto_now_add=True, verbose_name=_('Order creation date'))
    phone_number = models.CharField(max_length=20, verbose_name=_('Phone number'))
    requires_delivery = models.BooleanField(default=False, verbose_name=_('Delivery required'))
    delivery_address = models.TextField(null=True, blank=True, verbose_name=_('Delivery address'))
    payment_on_get = models.BooleanField(default=False, verbose_name=_('Payment on receipt'))
    is_paid = models.BooleanField(default=False, verbose_name=_('Paid'))
    status = models.CharField(max_length=50, default=_('In processing'), verbose_name=_('Order status'))

    class Meta:
        db_table = 'order'
        verbose_name = _('Order')
        verbose_name_plural = _('Orders')

    def __str__(self):
        return _("Order № {order} | Customer {customer_name} {customer_last_name}").format(
            order=self.pk,
            customer_name=self.user.first_name,
            customer_last_name=self.user.last_name
        )


class OrderItem(models.Model):
    order = models.ForeignKey(to=Order, on_delete=models.CASCADE, verbose_name=_('Order'))
    product = models.ForeignKey(to=Products, on_delete=models.SET_DEFAULT, null=True, blank=True,
                                verbose_name=_('Product'), default=None)
    name = models.CharField(max_length=150, verbose_name=_('Name'))
    price = models.DecimalField(max_digits=7, decimal_places=2, verbose_name=_('Price'))
    quantity = models.PositiveIntegerField(default=0, verbose_name=_('Quantity'))
    created_timestamp = models.DateTimeField(auto_now_add=True, verbose_name=_('Date of sale'))

    class Meta:
        db_table = 'order_item'
        verbose_name = _("Order item")
        verbose_name_plural = _("Order items")

    objects = OrderitemQuetySet.as_manager()

    def product_price(self):
        return round(self.price * self.quantity, 2)

    def __str__(self):
        return _('Item {name} | Order № {order}').format(
            name=self.name,
            order=self.order.pk
        )

orders/forms.py
import re

from django import forms
from django.utils.translation import gettext_lazy as _


class CreateOrderForm(forms.Form):
    first_name = forms.CharField()
    last_name = forms.CharField()
    phone_number = forms.CharField()
    requires_delivery = forms.ChoiceField(choices=[('0', False),
                                                   ('1', True)])
    delivery_address = forms.CharField(required=False)
    payment_on_get = forms.ChoiceField(choices=[('0', 'False'),
                                                ('1', 'True')])

    def clean_phone_number(self):
        data = self.cleaned_data['phone_number']

        allowed_chars = '()- '
        table = str.maketrans('', '', allowed_chars)

        data = data.translate(table)

        if not data.isdigit():
            raise forms.ValidationError(_('The phone number must contain only digits'))

        pattern = re.compile(r'^\d{10}$')
        if not pattern.match(data):
            raise forms.ValidationError(_('Incorrect phone number format'))

        return data

orders/views.py
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db import transaction
from django.forms import ValidationError
from django.shortcuts import redirect
from django.urls import reverse_lazy
from django.utils.translation import gettext_lazy as _
from django.views.generic import FormView

from carts.models import Cart
from orders.forms import CreateOrderForm
from orders.models import Order, OrderItem


class CreateOrderView(LoginRequiredMixin, FormView):
    template_name = 'orders/create_order.html'
    form_class = CreateOrderForm
    success_url = reverse_lazy('users:profile')

    def get_initial(self):
        initial = super().get_initial()
        initial['first_name'] = self.request.user.first_name
        initial['last_name'] = self.request.user.last_name
        return initial

    def form_valid(self, form):
        try:
            with transaction.atomic():
                user = self.request.user
                cart_items = Cart.objects.filter(user=user)

                if cart_items.exists():
                    # Create order
                    order = Order.objects.create(
                        user=user,
                        phone_number=form.cleaned_data['phone_number'],
                        requires_delivery=form.cleaned_data['requires_delivery'],
                        delivery_address=form.cleaned_data['delivery_address'],
                        payment_on_get=form.cleaned_data['payment_on_get'],
                    )
                    # Create ordered goods
                    for cart_item in cart_items:
                        product = cart_item.product
                        name = cart_item.product.name
                        price = cart_item.product.sell_price()
                        quantity = cart_item.quantity

                        if product.quantity < quantity:
                            raise ValidationError(_('Insufficient quantity of {name} in stock. In stock - {quantity}')
                            .format(
                                name=name,
                                quantity=product.quantity
                            ))

                        OrderItem.objects.create(
                            order=order,
                            product=product,
                            name=name,
                            price=price,
                            quantity=quantity,
                        )
                        product.quantity -= quantity
                        product.save()

                    # Clear cart after order creating
                    cart_items.delete()

                    messages.success(self.request, _('Order created!'))
                    return redirect('user:profile')
        except ValidationError as e:
            messages.success(self.request, str(e))
        return redirect('orders:create_order')

    def form_invalid(self, form):
        messages.error(self.request, _('Fill in all required fields!'))
        return redirect('orders:create_order')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = _('Order creation')
        context['order'] = True
        return context

orders/templates/orders/create_order.html
{% extends "base.html" %}
{% load static %}
{% load carts_tags %}
{% load i18n %}

{% block content %}
<div class=" bg-white p-4 mb-4 mx-2 rounded custom-shadow">
    <div class="container">
        <h3 class="text-center mb-4">{% translate 'Selected items' %}</h3>
        <div class="container" id="cart-items-container">
            <!-- Cart marking -->
            {% user_carts request as carts%}

            {% include "carts/includes/included_cart.html" %}
            <!-- Cart marking end -->
        </div>
    </div>
    <!-- Order details -->
    <div class="container">
        <h3 class="text-center">{% translate 'Order details' %}</h3>
        <div class="card mb-3">
            <div class="card-body">
                <form action="{% url "orders:create_order" %}" method="post">
                {% csrf_token %}
                    <div class="row">
                        <div class="col-md-6 mb-3">
                            <label for="id_first_name" class="form-label">{% translate 'First name' %}*:</label>
                            <input type="text" class="form-control" id="id_first_name"
                                   value="{% if form.first_name.value %}{{form.first_name.value}}{%endif%}"
                                   name="first_name" required>
                            {% if form.first_name.errors%}
                            <div class="alert alert-danger alert-dismissible fade show"> {{form.first_name.errors}} </div>
                            {% endif %}
                        </div>
                        <div class="col-md-6 mb-3">
                            <label for="id_last_name" class="form-label">{% translate 'Last name' %}*:</label>
                            <input type="text" class="form-control" id="id_last_name"
                                   value="{% if form.last_name.value %}{{form.last_name.value}}{%endif%}"
                                   name="last_name" required>
                            {% if form.last_name.errors%}
                            <div class="alert alert-danger alert-dismissible fade show"> {{form.last_name.errors}} </div>
                            {% endif %}
                        </div>
                        <div class="col-md-6 mb-3">
                            <label for="id_phone_number" class="form-label">{% translate 'Phone number' %}*:</label>
                            <input type="text" class="form-control" id="id_phone_number" name="phone_number"
                                   value="{% if form.phone_number.value %}{{form.phone_number.value}}{%endif%}"
                                   placeholder="В формате: XXX-XXX-XX-XX"
                                   required>
                            {% if form.phone_number.errors%}
                            <div class="alert alert-danger alert-dismissible fade show"> {{form.phone_number.errors}} </div>
                            {% endif %}
                        </div>
                        <div class="col-md-12 mb-3">
                            <label for="delivery" class="form-label">{% translate 'Delivery method' %}: </label>
                            <div class="form-check form-check-inline">
                                <input class="form-check-input" type="radio" name="requires_delivery"
                                       id="id_requires_delivery" value="1" checked>
                                <label class="form-check-label" for="id_requires_delivery">{% translate 'Delivery required' %}</label>
                            </div>
                            <div class="form-check form-check-inline">
                                <input class="form-check-input" type="radio" name="requires_delivery"
                                       id="id_requires_delivery" value="0">
                                <label class="form-check-label" for="id_requires_delivery">{% translate 'Self-delivery' %}</label>
                            </div>
                        </div>
                        <div class="mb-3" id="deliveryAddressField">
                            <label for="id_delivery_address" class="form-label">{% translate 'Delivery address' %}*:</label>
                            <textarea class="form-control" id="id_delivery_address"
                                      value="{% if form.delivery_address.value %}{{form.delivery_address.value}}{%endif%}"
                                      name="delivery_address" rows="2"></textarea>
                            {% if form.delivery_address.errors%}
                            <div class="alert alert-danger alert-dismissible fade show"> {{form.delivery_address.errors}} </div>
                            {% endif %}
                        </div>
                        <div class="col-md-12 mb-3">
                            <label class="form-label">{% translate 'Payment method' %}: </label>
                            <div class="form-check form-check-inline">
                                <input class="form-check-input" type="radio" name="payment_on_get"
                                       id="id_payment_on_get" value="0" checked>
                                <label class="form-check-label" for="id_payment_on_get">{% translate 'Card payment' %}</label>
                            </div>
                            <div class="form-check form-check-inline">
                                <input class="form-check-input" type="radio" name="payment_on_get"
                                       id="id_payment_on_get" value="1">
                                <label class="form-check-label" for="id_payment_on_get">{% translate 'Cash/card on receipt' %}</label>
                                {% if form.payment_on_get.errors%}
                                <div class="alert alert-danger alert-dismissible fade show"> {{form.payment_on_get.errors}} </div>
                                {% endif %}
                            </div>
                        </div>
                    </div>
                    <button type="submit" class="btn btn-dark">{% translate 'Create order' %}</button>
                </form>
            </div>
        </div>
    </div>
</div>
{%  endblock %}